language: python

python:
    - "2.7"

install:
    - "pip install -q -r requirements/dev.txt ."

before_script:
  - "pep8 {{cookiecutter.repo_name}}"
  - "pyflakes {{cookiecutter.repo_name}}"

script:
    - coverage run --source {{cookiecutter.repo_name}} setup.py test

after_success:
    coveralls

notifications:
    email: false
